spring.application.name=web-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-3xpqpzjayt0s15u2.us.auth0.com/

auth0.audience=https://UberClocked-api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
mp.api-token=${MP_TOKEN}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

app.admin.emails=santinocolombo13@gmail.com,santiagogarrote2005@gmail.com